version: '3.8'

services:
  app:
    build: .
    container_name: gateway-gaming
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    container_name: redis-local
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env
    restart: always

volumes:
  redis_data:
